In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import requests

In [2]:
#import csv data from 2020 to 2024
nba_data2023_2024 = pd.read_csv('nba2023-2024.csv', encoding='latin1', sep=';')
nba_data2022_2023 = pd.read_csv('nba2022-2023.csv', encoding='latin1', sep=';')
nba_data2021_2022 = pd.read_csv('nba2021-2022.csv', encoding='latin1', sep=';')
print(nba_data2023_2024.info())
print(nba_data2022_2023.info())
print(nba_data2021_2022.info())
#i have to deal with season 2020-2021 and season 2019-20 differently as data is in a different format

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 735 entries, 0 to 734
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      735 non-null    int64
 1   Player  735 non-null    object
 2   Pos     735 non-null    object
 3   Age     735 non-null    int64
 4   Tm      735 non-null    object
 5   G       735 non-null    int64
 6   GS      735 non-null    int64
 7   MP      735 non-null    float64
 8   FG      735 non-null    float64
 9   FGA     735 non-null    float64
 10  FG%     735 non-null    float64
 11  3P      735 non-null    float64
 12  3PA     735 non-null    float64
 13  3P%     735 non-null    float64
 14  2P      735 non-null    float64
 15  2PA     735 non-null    float64
 16  2P%     735 non-null    float64
 17  eFG%    735 non-null    float64
 18  FT      735 non-null    float64
 19  FTA     735 non-null    float64
 20  FT%     735 non-null    float64
 21  ORB     735 non-null    float64
 22  DRB     735 non-null    float64
 23  TRB     735 non-null    float64
 24  AST     735 non-null    float64
 25  STL     735 non-null    float64
 26  BLK     735 non-null    float64
 27  TOV     735 non-null    float64
 28  PF      735 non-null    float64
 29  PTS     735 non-null    float64
dtypes: float64(23), int64(4), object(3)
memory usage: 172.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      217 non-null    int64
 1   Player  217 non-null    object
 2   Pos     217 non-null    object
 3   Age     217 non-null    int64
 4   Tm      217 non-null    object
 5   G       217 non-null    int64
 6   GS      217 non-null    int64
 7   MP      217 non-null    float64
 8   FG      217 non-null    float64
 9   FGA     217 non-null    float64
 10  FG%     217 non-null    float64
 11  3P      217 non-null    float64
 12  3PA     217 non-null    float64
 13  3P%     217 non-null    float64
 14  2P      217 non-null    float64
 15  2PA     217 non-null    float64
 16  2P%     217 non-null    float64
 17  eFG%    217 non-null    float64
 18  FT      217 non-null    float64
 19  FTA     217 non-null    float64
 20  FT%     217 non-null    float64
 21  ORB     217 non-null    float64
 22  DRB     217 non-null    float64
 23  TRB     217 non-null    float64
 24  AST     217 non-null    float64
 25  STL     217 non-null    float64
 26  BLK     217 non-null    float64
 27  TOV     217 non-null    float64
 28  PF      217 non-null    float64
 29  PTS     217 non-null    float64
dtypes: float64(23), int64(4), object(3)
memory usage: 51.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 812 entries, 0 to 811
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      812 non-null    int64
 1   Player  812 non-null    object
 2   Pos     812 non-null    object
 3   Age     812 non-null    int64
 4   Tm      812 non-null    object
 5   G       812 non-null    int64
 6   GS      812 non-null    int64
 7   MP      812 non-null    float64
 8   FG      812 non-null    float64
 9   FGA     812 non-null    float64
 10  FG%     812 non-null    float64
 11  3P      812 non-null    float64
 12  3PA     812 non-null    float64
 13  3P%     812 non-null    float64
 14  2P      812 non-null    float64
 15  2PA     812 non-null    float64
 16  2P%     812 non-null    float64
 17  eFG%    812 non-null    float64
 18  FT      812 non-null    float64
 19  FTA     812 non-null    float64
 20  FT%     812 non-null    float64
 21  ORB     812 non-null    float64
 22  DRB     812 non-null    float64
 23  TRB     812 non-null    float64
 24  AST     812 non-null    float64
 25  STL     812 non-null    float64
 26  BLK     812 non-null    float64
 27  TOV     812 non-null    float64
 28  PF      812 non-null    float64
 29  PTS     812 non-null    float64
dtypes: float64(23), int64(4), object(3)
memory usage: 190.4+ KB
None

In [3]:
#spliting columns and assigning the names as the original data didn't include headeers
nba_data2020_2021 = pd.read_csv('nba2020-2021.csv', encoding='latin1', sep=';', header=None)
nba_data2020_2021 = nba_data2020_2021[0].str.split(',', expand=True)
nba_data2020_2021.columns = [
    'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 
    '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 
    'BLK', 'TOV', 'PF', 'PTS'
]
#converting columns that contain numeric data into numeric format
numeric_columns = [
    'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 
    'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'
]
nba_data2020_2021[numeric_columns] = nba_data2020_2021[numeric_columns].apply(pd.to_numeric, errors='coerce')
nba_data2020_2021_cleaned = nba_data2020_2021.drop(index=0).reset_index(drop=True)
print(nba_data2020_2021_cleaned.head())
print(nba_data2020_2021_cleaned.info())

              Player Pos   Age   Tm     G    GS    MP   FG   FGA    FG%  ...  \
0   Precious Achiuwa  PF  21.0  MIA  28.0   2.0  14.6  2.6   4.4  0.590  ...
1       Jaylen Adams  PG  24.0  MIL   6.0   0.0   2.8  0.2   1.3  0.125  ...
2       Steven Adams   C  27.0  NOP  27.0  27.0  28.1  3.5   5.8  0.603  ...
3        Bam Adebayo   C  23.0  MIA  26.0  26.0  33.6  7.4  12.9  0.573  ...
4  LaMarcus Aldridge   C  35.0  SAS  18.0  18.0  26.7  5.9  12.5  0.476  ...

     FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS
0  0.561  1.3  2.7  4.0  0.6  0.4  0.5  1.0  1.9   6.5
1  0.000  0.0  0.5  0.5  0.3  0.0  0.0  0.0  0.2   0.3
2  0.468  4.3  4.6  8.9  2.1  1.0  0.6  1.7  1.9   8.0
3  0.841  1.9  7.3  9.2  5.3  1.0  1.0  3.0  2.6  19.9
4  0.762  0.8  3.5  4.3  1.9  0.4  0.9  0.9  1.5  14.1

[5 rows x 29 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  497 non-null    object
 1   Pos     497 non-null    object
 2   Age     497 non-null    float64
 3   Tm      497 non-null    object
 4   G       497 non-null    float64
 5   GS      497 non-null    float64
 6   MP      497 non-null    float64
 7   FG      497 non-null    float64
 8   FGA     497 non-null    float64
 9   FG%     497 non-null    float64
 10  3P      497 non-null    float64
 11  3PA     497 non-null    float64
 12  3P%     497 non-null    float64
 13  2P      497 non-null    float64
 14  2PA     497 non-null    float64
 15  2P%     497 non-null    float64
 16  eFG%    497 non-null    float64
 17  FT      497 non-null    float64
 18  FTA     497 non-null    float64
 19  FT%     497 non-null    float64
 20  ORB     497 non-null    float64
 21  DRB     497 non-null    float64
 22  TRB     497 non-null    float64
 23  AST     497 non-null    float64
 24  STL     497 non-null    float64
 25  BLK     497 non-null    float64
 26  TOV     497 non-null    float64
 27  PF      497 non-null    float64
 28  PTS     497 non-null    float64
dtypes: float64(26), object(3)
memory usage: 112.7+ KB
None

In [4]:
#data scrapping season 2019-2020
def scrape_team_per_game(team_initial):
    url = f"https://www.basketball-reference.com/teams/{team_initial}/2020.html#all_per_game-playoffs_per_game"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    table = soup.find('table', {'id':'per_game'})
    headers = [th.text for th in table.find('thead').find_all('th')]
    rows = table.find('tbody').find_all('tr')
    data =[]
    for row in rows:
        cells = row.find_all('td')
        cells = [cell.text.strip() for cell in cells]
        data.append(cells)
    df = pd.DataFrame(data, columns=headers[1:])  #skipping the first header which is the rank column
    df['Team'] = team_initial  

    return df
#listing the initials of each team to put in the url
teams = [
    "MIL", "ATL", "BOS", "BRK", "CHO", "CHI", "CLE", "DAL", "DEN", "DET",
    "GSW", "HOU", "IND", "LAC", "LAL", "MEM", "MIA", "MIN", "NOP", "NYK",
    "OKC", "ORL", "PHI", "PHO", "POR", "SAC", "SAS", "TOR", "UTA", "WAS"
]
nba_data2019_2020 = pd.DataFrame()
for team in teams:
    team_data = scrape_team_per_game(team)
    if not team_data.empty:
        nba_data2019_2020 = pd.concat([nba_data2019_2020, team_data], ignore_index=True)
print(nba_data2019_2020.info())
print(nba_data2019_2020.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  591 non-null    object
 1   Age     591 non-null    object
 2   G       591 non-null    object
 3   GS      591 non-null    object
 4   MP      591 non-null    object
 5   FG      591 non-null    object
 6   FGA     591 non-null    object
 7   FG%     591 non-null    object
 8   3P      591 non-null    object
 9   3PA     591 non-null    object
 10  3P%     591 non-null    object
 11  2P      591 non-null    object
 12  2PA     591 non-null    object
 13  2P%     591 non-null    object
 14  eFG%    591 non-null    object
 15  FT      591 non-null    object
 16  FTA     591 non-null    object
 17  FT%     591 non-null    object
 18  ORB     591 non-null    object
 19  DRB     591 non-null    object
 20  TRB     591 non-null    object
 21  AST     591 non-null    object
 22  STL     591 non-null    object
 23  BLK     591 non-null    object
 24  TOV     591 non-null    object
 25  PF      591 non-null    object
 26  PTS     591 non-null    object
 27  Team    591 non-null    object
dtypes: object(28)
memory usage: 129.4+ KB
None
                  Player Age   G  GS    MP    FG   FGA   FG%   3P  3PA  ...  \
0  Giannis Antetokounmpo  25  63  63  30.4  10.9  19.7  .553  1.4  4.7  ...
1        Khris Middleton  28  62  59  29.9   7.6  15.3  .497  2.4  5.7  ...
2           Eric Bledsoe  30  61  61  27.0   5.5  11.5  .475  1.2  3.5  ...
3            Brook Lopez  31  68  67  26.7   4.3   9.9  .435  1.5  4.8  ...
4        Wesley Matthews  33  67  67  24.4   2.5   6.3  .396  1.6  4.4  ...

   ORB   DRB   TRB  AST  STL  BLK  TOV   PF   PTS Team
0  2.2  11.4  13.6  5.6  1.0  1.0  3.7  3.1  29.5  MIL
1  0.7   5.5   6.2  4.3  0.9  0.1  2.2  2.3  20.9  MIL
2  0.7   3.9   4.6  5.4  0.9  0.4  2.4  2.1  14.9  MIL
3  0.9   3.7   4.6  1.5  0.7  2.4  1.0  2.4  12.0  MIL
4  0.3   2.1   2.5  1.4  0.6  0.1  0.6  1.5   7.4  MIL

[5 rows x 28 columns]

In [14]:
print(nba_data2019_2020.columns)

Index(['Player', 'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA',
       '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB',
       'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Team'],
      dtype='object')

In [15]:
#changing columns that are numeric to numeric type
nba_data2019_2020.columns = [
    'Player', 'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', 
    '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 
    'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Team'
]
numeric_columns = [
    'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 
    'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'
]
nba_data2019_2020[numeric_columns] = nba_data2019_2020[numeric_columns].apply(pd.to_numeric, errors='coerce')
nba_data2019_2020_cleaned = nba_data2019_2020.drop(index=0).reset_index(drop=True)
print(nba_data2019_2020_cleaned.head())
print(nba_data2019_2020_cleaned.info())

             Player  Age   G  GS    MP   FG   FGA    FG%   3P  3PA  ...  ORB  \
0   Khris Middleton   28  62  59  29.9  7.6  15.3  0.497  2.4  5.7  ...  0.7
1      Eric Bledsoe   30  61  61  27.0  5.5  11.5  0.475  1.2  3.5  ...  0.7
2       Brook Lopez   31  68  67  26.7  4.3   9.9  0.435  1.5  4.8  ...  0.9
3   Wesley Matthews   33  67  67  24.4  2.5   6.3  0.396  1.6  4.4  ...  0.3
4  Donte DiVincenzo   23  66  24  23.0  3.5   7.7  0.455  1.3  3.7  ...  1.0

   DRB  TRB  AST  STL  BLK  TOV   PF   PTS  Team
0  5.5  6.2  4.3  0.9  0.1  2.2  2.3  20.9   MIL
1  3.9  4.6  5.4  0.9  0.4  2.4  2.1  14.9   MIL
2  3.7  4.6  1.5  0.7  2.4  1.0  2.4  12.0   MIL
3  2.1  2.5  1.4  0.6  0.1  0.6  1.5   7.4   MIL
4  3.8  4.8  2.3  1.3  0.3  1.4  1.7   9.2   MIL

[5 rows x 28 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590 entries, 0 to 589
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  590 non-null    object
 1   Age     590 non-null    int64
 2   G       590 non-null    int64
 3   GS      590 non-null    int64
 4   MP      590 non-null    float64
 5   FG      590 non-null    float64
 6   FGA     590 non-null    float64
 7   FG%     588 non-null    float64
 8   3P      590 non-null    float64
 9   3PA     590 non-null    float64
 10  3P%     557 non-null    float64
 11  2P      590 non-null    float64
 12  2PA     590 non-null    float64
 13  2P%     584 non-null    float64
 14  eFG%    588 non-null    float64
 15  FT      590 non-null    float64
 16  FTA     590 non-null    float64
 17  FT%     557 non-null    float64
 18  ORB     590 non-null    float64
 19  DRB     590 non-null    float64
 20  TRB     590 non-null    float64
 21  AST     590 non-null    float64
 22  STL     590 non-null    float64
 23  BLK     590 non-null    float64
 24  TOV     590 non-null    float64
 25  PF      590 non-null    float64
 26  PTS     590 non-null    float64
 27  Team    590 non-null    object
dtypes: float64(23), int64(3), object(2)
memory usage: 129.2+ KB
None

In [43]:
#looking for data that is missing values, to check why they are missing on the original webpage
missing_data_rows = nba_data2019_2020_cleaned[
    nba_data2019_2020_cleaned['3P%'].isna() |
    nba_data2019_2020_cleaned['eFG%'].isna() |
    nba_data2019_2020_cleaned['FT%'].isna() |
    nba_data2019_2020_cleaned['FG%'].isna()
]

print(missing_data_rows)
#data is missing because they didn't attempt any FT (e.g. if FT is 0, FT% is empty)

                   Player  Age   G  GS    MP   FG  FGA    FG%   3P  3PA  ...  \
34       Chandler Parsons   31   5   0  10.8  1.0  3.6  0.278  0.8  2.8  ...
35            Paul Watson   25   2   0   8.5  0.0  3.5  0.000  0.0  1.5  ...
47        Robert Williams   22  29   1  13.4  2.2  3.0  0.727  0.0  0.0  ...
53             Tacko Fall   24   7   0   4.7  1.6  2.0  0.786  0.0  0.0  ...
62         DeAndre Jordan   31  56   6  22.0  3.4  5.1  0.666  0.0  0.0  ...
66             Donta Hall   22   5   0  17.0  2.8  3.6  0.778  0.0  0.0  ...
76         Jamal Crawford   39   1   0   6.0  2.0  4.0  0.500  1.0  2.0  ...
77         Henry Ellenson   23   5   0   3.0  0.2  1.4  0.143  0.0  0.8  ...
86        Bismack Biyombo   27  53  29  19.4  2.8  5.2  0.543  0.0  0.0  ...
106        Daniel Gafford   21  43   7  14.2  2.2  3.1  0.701  0.0  0.0  ...
125            Ante Žižić   23  22   0  10.0  1.9  3.3  0.569  0.0  0.0  ...
127           Matt Mooney   23   4   0   4.8  0.3  1.0  0.250  0.0  0.5  ...
129            Tyler Cook   22  11   0   3.2  0.6  0.9  0.700  0.0  0.0  ...
130        Marques Bolden   21   1   0   3.0  0.0  0.0    NaN  0.0  0.0  ...
131           J.P. Macura   24   1   0   1.0  0.0  0.0    NaN  0.0  0.0  ...
164          Troy Daniels   28   6   0  12.7  1.7  4.7  0.357  1.0  3.3  ...
167            Tyler Cook   22   2   0   9.5  0.5  1.0  0.500  0.0  0.0  ...
169     Jarred Vanderbilt   20   9   0   4.6  0.6  0.8  0.714  0.0  0.0  ...
189            Donta Hall   22   4   0  12.0  0.3  1.0  0.250  0.0  0.0  ...
190        Derrick Walton   24   3   0   8.7  0.3  1.0  0.333  0.3  1.0  ...
193           Jordan Bone   22  10   0   5.3  0.5  2.0  0.250  0.2  1.0  ...
203   Willie Cauley-Stein   26  41  37  22.9  3.5  6.3  0.560  0.0  0.0  ...
220          Clint Capela   25  39  39  32.8  6.3  9.9  0.629  0.0  0.0  ...
232        Tyson Chandler   37  26   5   8.4  0.5  0.7  0.778  0.0  0.0  ...
234         Ryan Anderson   31   2   0   7.0  1.0  3.5  0.286  0.5  2.5  ...
235        William Howard   26   2   0   6.5  0.0  2.0  0.000  0.0  2.0  ...
249       Naz Mitrou-Long   26   5   0   9.4  1.2  3.4  0.353  0.4  2.4  ...
253           Brian Bowen   21   6   1   5.2  0.5  1.7  0.300  0.0  0.3  ...
268           Joakim Noah   34   5   0  10.0  0.8  1.6  0.500  0.0  0.0  ...
290        Devontae Cacok   23   1   0   9.0  3.0  6.0  0.500  0.0  0.0  ...
292  Kostas Antetokounmpo   22   5   0   4.0  0.6  0.6  1.000  0.0  0.0  ...
293          Zach Norvell   22   2   0   2.5  0.0  0.5  0.000  0.0  0.0  ...
331          Gabe Vincent   23   9   0   9.2  0.9  4.1  0.216  0.7  3.0  ...
333        Kyle Alexander   23   2   0   6.5  0.5  1.0  0.500  0.0  0.0  ...
335           Daryl Macon   24   4   0   3.5  0.3  0.8  0.333  0.3  0.5  ...
359           Jacob Evans   22   2   0   2.0  0.0  0.5  0.000  0.0  0.5  ...
374        Zylan Cheatham   24   4   0  12.8  1.5  2.3  0.667  0.0  0.3  ...
376             Josh Gray   26   2   0  11.5  0.5  1.0  0.500  0.0  0.0  ...
383     Mitchell Robinson   21  61   7  23.1  4.1  5.6  0.742  0.0  0.0  ...
409          Kevin Hervey   23  10   0   5.2  0.7  2.7  0.259  0.3  2.0  ...
410         Justin Patton   22   5   0   4.8  0.8  2.0  0.400  0.2  0.8  ...
411           Isaiah Roby   21   3   0   3.7  0.0  0.3  0.000  0.0  0.0  ...
430       Amile Jefferson   26  18   0   4.1  0.3  0.8  0.357  0.0  0.0  ...
468          Jared Harper   22   3   0   2.7  0.3  1.3  0.250  0.0  0.7  ...
487           Moses Brown   20   9   0   3.7  0.4  1.1  0.400  0.0  0.0  ...
492        Richaun Holmes   26  44  38  28.2  5.1  7.8  0.648  0.0  0.0  ...
498             Eric Mika   25   1   0  19.0  2.0  3.0  0.667  0.0  0.0  ...
509              Kyle Guy   22   3   0   3.3  0.7  1.7  0.400  0.0  1.0  ...
510        Caleb Swanigan   22   7   0   3.3  0.3  0.6  0.500  0.0  0.0  ...
520          Jakob Poeltl   24  66  18  17.7  2.5  4.0  0.624  0.0  0.0  ...
528          Tyler Zeller   30   2   0   2.0  0.5  2.0  0.250  0.0  0.0  ...
547           Rudy Gobert   27  68  68  34.3  5.7  8.2  0.693  0.0  0.0  ...
560              Ed Davis   30  28   1  10.8  0.8  1.6  0.478  0.0  0.0  ...
566          Stanton Kidd   27   4   0   3.8  0.0  0.8  0.000  0.0  0.3  ...
584         Jarrod Uthoff   26   3   0  13.0  2.0  3.7  0.545  1.0  1.7  ...
586         Chris Chiozza   24  10   0  12.3  1.0  3.4  0.294  0.7  1.6  ...
589       Justin Robinson   22   9   0   5.4  0.6  1.3  0.417  0.3  0.6  ...

      DRB   TRB  AST  STL  BLK  TOV   PF   PTS   Tm  Pos
34    1.2   1.4  0.6  0.8  0.2  0.6  0.6   2.8  ATL  NaN
35    1.0   1.0  1.5  0.5  0.0  0.0  0.5   0.0  ATL   SF
47    3.0   4.4  0.9  0.8  1.2  0.7  1.8   5.2  BOS    C
53    2.0   2.1  0.1  0.1  0.6  0.4  1.0   3.3  BOS    C
62    7.5  10.0  1.9  0.3  0.9  1.3  2.0   8.3  BRK    C
66    3.0   4.6  0.4  0.4  1.0  0.6  2.8   6.6  BRK  NaN
76    0.0   0.0  3.0  0.0  0.0  0.0  1.0   5.0  BRK  NaN
77    0.8   1.2  0.2  0.0  0.0  0.0  0.2   0.4  BRK  NaN
86    3.5   5.8  0.9  0.2  0.9  0.9  2.2   7.4  CHO    C
106   1.3   2.5  0.5  0.3  1.3  0.7  2.3   5.1  CHI    C
125   2.2   3.0  0.3  0.3  0.2  0.5  1.2   4.4  CLE  NaN
127   0.8   0.8  0.3  0.5  0.3  0.0  0.3   0.5  CLE   SG
129   0.5   0.9  0.1  0.1  0.0  0.1  0.4   1.7  CLE   PF
130   2.0   2.0  0.0  1.0  0.0  0.0  1.0   0.0  CLE    C
131   0.0   0.0  0.0  0.0  0.0  0.0  0.0   0.0  CLE  NaN
164   1.0   1.0  0.5  0.5  0.0  0.5  1.2   4.3  DEN  NaN
167   1.0   2.0  0.0  1.0  0.0  1.0  0.5   2.0  DEN   PF
169   0.6   0.9  0.2  0.3  0.1  0.8  0.7   1.1  DEN   PF
189   2.3   3.8  0.5  0.3  0.3  0.5  2.3   1.5  DET  NaN
190   0.3   0.3  1.7  1.0  0.0  0.3  0.7   1.0  DET   PG
193   0.4   0.4  0.8  0.1  0.0  0.2  0.6   1.2  DET   PG
203   4.5   6.2  1.5  1.1  1.2  0.9  2.5   7.9  GSW    C
220   9.5  13.8  1.2  0.8  1.8  1.6  2.6  13.9  HOU    C
232   1.6   2.5  0.2  0.2  0.3  0.3  1.2   1.3  HOU  NaN
234   3.5   3.5  1.0  0.5  0.0  0.5  0.5   2.5  HOU  NaN
235   1.0   1.0  0.5  0.0  0.0  0.5  0.5   0.0  HOU  NaN
249   1.4   1.4  1.6  0.2  0.2  0.6  0.4   2.8  IND  NaN
253   1.0   1.2  0.0  0.0  0.2  0.2  0.5   1.0  IND   SF
268   2.2   3.2  1.4  0.2  0.2  1.2  1.8   2.8  LAC  NaN
290   3.0   5.0  1.0  0.0  0.0  0.0  0.0   6.0  LAL   PF
292   0.2   0.6  0.4  0.0  0.0  0.2  0.4   1.4  LAL   PF
293   0.5   0.5  0.0  0.0  0.0  0.0  0.0   0.0  LAL  NaN
331   0.6   0.6  0.7  0.6  0.0  0.1  0.7   2.4  MIA   PG
333   0.5   1.5  0.0  0.0  0.0  0.5  0.5   1.0  MIA  NaN
335   0.0   0.0  0.3  0.0  0.0  0.5  0.3   0.8  MIA  NaN
359   0.0   0.0  0.0  0.0  0.0  0.0  0.0   0.0  MIN  NaN
374   1.5   2.3  0.8  0.3  0.3  1.0  2.5   3.0  NOP   SF
376   0.5   1.0  1.0  0.0  0.0  2.5  0.5   1.0  NOP  NaN
383   4.0   7.0  0.6  0.9  2.0  0.6  3.2   9.7  NYK    C
409   1.1   1.2  0.5  0.1  0.1  0.0  0.4   1.7  OKC  NaN
410   0.8   1.0  0.4  0.0  0.0  0.4  0.8   1.8  OKC  NaN
411   0.7   0.7  0.0  0.0  0.0  0.3  0.3   0.0  OKC   PF
430   0.7   1.3  0.2  0.1  0.2  0.2  0.4   0.8  ORL  NaN
468   0.0   0.0  0.0  0.0  0.0  0.0  0.0   0.7  PHO   PG
487   1.2   1.6  0.1  0.1  0.1  0.3  0.8   1.2  POR    C
492   5.3   8.1  1.0  0.9  1.3  1.2  3.8  12.3  SAC    C
498   5.0   7.0  0.0  0.0  0.0  0.0  5.0   6.0  SAC  NaN
509   0.3   0.3  0.3  0.0  0.0  0.0  0.3   1.3  SAC   PG
510   0.7   1.0  0.3  0.1  0.3  0.9  1.1   0.7  SAC  NaN
520   3.7   5.7  1.8  0.6  1.4  0.8  1.9   5.6  SAS    C
528   0.5   2.0  0.0  0.0  0.0  0.0  0.0   1.0  SAS  NaN
547  10.1  13.5  1.5  0.8  2.0  1.9  3.2  15.1  UTA    C
560   2.5   3.8  0.4  0.4  0.3  0.5  2.2   1.8  UTA    C
566   0.8   0.8  0.3  0.0  0.0  0.5  0.8   0.0  UTA  NaN
584   1.3   1.7  0.0  0.0  0.0  0.0  0.3   5.0  WAS  NaN
586   1.5   1.5  2.8  1.0  0.2  0.9  1.2   2.7  WAS   PG
589   0.4   0.6  0.8  0.0  0.1  0.3  0.2   1.4  WAS   PG

[57 rows x 29 columns]

In [46]:
#filling empty data with 0, as this is the true value
nba_data2019_2020_cleaned['FT%'].fillna(0, inplace=True)
nba_data2019_2020_cleaned['3P%'].fillna(0, inplace=True)
nba_data2019_2020_cleaned['FG%'].fillna(0, inplace=True)
nba_data2019_2020_cleaned['eFG%'].fillna(0, inplace=True)
nba_data2019_2020_cleaned['2P%'].fillna(0, inplace=True)
print(nba_data2019_2020_cleaned.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590 entries, 0 to 589
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  590 non-null    object
 1   Age     590 non-null    int64
 2   G       590 non-null    int64
 3   GS      590 non-null    int64
 4   MP      590 non-null    float64
 5   FG      590 non-null    float64
 6   FGA     590 non-null    float64
 7   FG%     590 non-null    float64
 8   3P      590 non-null    float64
 9   3PA     590 non-null    float64
 10  3P%     590 non-null    float64
 11  2P      590 non-null    float64
 12  2PA     590 non-null    float64
 13  2P%     590 non-null    float64
 14  eFG%    590 non-null    float64
 15  FT      590 non-null    float64
 16  FTA     590 non-null    float64
 17  FT%     590 non-null    float64
 18  ORB     590 non-null    float64
 19  DRB     590 non-null    float64
 20  TRB     590 non-null    float64
 21  AST     590 non-null    float64
 22  STL     590 non-null    float64
 23  BLK     590 non-null    float64
 24  TOV     590 non-null    float64
 25  PF      590 non-null    float64
 26  PTS     590 non-null    float64
 27  Tm      590 non-null    object
 28  Pos     458 non-null    object
dtypes: float64(23), int64(3), object(3)
memory usage: 133.8+ KB
None

In [47]:
#check data again before concatenating
print(nba_data2019_2020_cleaned.head()) #no rank column, only need to change team to tm, no Pos column
print(nba_data2019_2020_cleaned.info())
print(nba_data2020_2021_cleaned.head()) #no rank column
print(nba_data2020_2021_cleaned.info())
print(nba_data2021_2022.head()) #need to drop rank column
print(nba_data2021_2022.info())
print(nba_data2022_2023.head()) #need to drop rank column
print(nba_data2022_2023.info())
print(nba_data2023_2024.head()) #need to drop rank column
print(nba_data2023_2024.info())

             Player  Age   G  GS    MP   FG   FGA    FG%   3P  3PA  ...  DRB  \
0   Khris Middleton   28  62  59  29.9  7.6  15.3  0.497  2.4  5.7  ...  5.5
1      Eric Bledsoe   30  61  61  27.0  5.5  11.5  0.475  1.2  3.5  ...  3.9
2       Brook Lopez   31  68  67  26.7  4.3   9.9  0.435  1.5  4.8  ...  3.7
3   Wesley Matthews   33  67  67  24.4  2.5   6.3  0.396  1.6  4.4  ...  2.1
4  Donte DiVincenzo   23  66  24  23.0  3.5   7.7  0.455  1.3  3.7  ...  3.8

   TRB  AST  STL  BLK  TOV   PF   PTS   Tm  Pos
0  6.2  4.3  0.9  0.1  2.2  2.3  20.9  MIL   SF
1  4.6  5.4  0.9  0.4  2.4  2.1  14.9  MIL   PG
2  4.6  1.5  0.7  2.4  1.0  2.4  12.0  MIL    C
3  2.5  1.4  0.6  0.1  0.6  1.5   7.4  MIL   SG
4  4.8  2.3  1.3  0.3  1.4  1.7   9.2  MIL   SG

[5 rows x 29 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590 entries, 0 to 589
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  590 non-null    object
 1   Age     590 non-null    int64
 2   G       590 non-null    int64
 3   GS      590 non-null    int64
 4   MP      590 non-null    float64
 5   FG      590 non-null    float64
 6   FGA     590 non-null    float64
 7   FG%     590 non-null    float64
 8   3P      590 non-null    float64
 9   3PA     590 non-null    float64
 10  3P%     590 non-null    float64
 11  2P      590 non-null    float64
 12  2PA     590 non-null    float64
 13  2P%     590 non-null    float64
 14  eFG%    590 non-null    float64
 15  FT      590 non-null    float64
 16  FTA     590 non-null    float64
 17  FT%     590 non-null    float64
 18  ORB     590 non-null    float64
 19  DRB     590 non-null    float64
 20  TRB     590 non-null    float64
 21  AST     590 non-null    float64
 22  STL     590 non-null    float64
 23  BLK     590 non-null    float64
 24  TOV     590 non-null    float64
 25  PF      590 non-null    float64
 26  PTS     590 non-null    float64
 27  Tm      590 non-null    object
 28  Pos     458 non-null    object
dtypes: float64(23), int64(3), object(3)
memory usage: 133.8+ KB
None
              Player Pos   Age   Tm     G    GS    MP   FG   FGA    FG%  ...  \
0   Precious Achiuwa  PF  21.0  MIA  28.0   2.0  14.6  2.6   4.4  0.590  ...
1       Jaylen Adams  PG  24.0  MIL   6.0   0.0   2.8  0.2   1.3  0.125  ...
2       Steven Adams   C  27.0  NOP  27.0  27.0  28.1  3.5   5.8  0.603  ...
3        Bam Adebayo   C  23.0  MIA  26.0  26.0  33.6  7.4  12.9  0.573  ...
4  LaMarcus Aldridge   C  35.0  SAS  18.0  18.0  26.7  5.9  12.5  0.476  ...

     FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS
0  0.561  1.3  2.7  4.0  0.6  0.4  0.5  1.0  1.9   6.5
1  0.000  0.0  0.5  0.5  0.3  0.0  0.0  0.0  0.2   0.3
2  0.468  4.3  4.6  8.9  2.1  1.0  0.6  1.7  1.9   8.0
3  0.841  1.9  7.3  9.2  5.3  1.0  1.0  3.0  2.6  19.9
4  0.762  0.8  3.5  4.3  1.9  0.4  0.9  0.9  1.5  14.1

[5 rows x 29 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  497 non-null    object
 1   Pos     497 non-null    object
 2   Age     497 non-null    float64
 3   Tm      497 non-null    object
 4   G       497 non-null    float64
 5   GS      497 non-null    float64
 6   MP      497 non-null    float64
 7   FG      497 non-null    float64
 8   FGA     497 non-null    float64
 9   FG%     497 non-null    float64
 10  3P      497 non-null    float64
 11  3PA     497 non-null    float64
 12  3P%     497 non-null    float64
 13  2P      497 non-null    float64
 14  2PA     497 non-null    float64
 15  2P%     497 non-null    float64
 16  eFG%    497 non-null    float64
 17  FT      497 non-null    float64
 18  FTA     497 non-null    float64
 19  FT%     497 non-null    float64
 20  ORB     497 non-null    float64
 21  DRB     497 non-null    float64
 22  TRB     497 non-null    float64
 23  AST     497 non-null    float64
 24  STL     497 non-null    float64
 25  BLK     497 non-null    float64
 26  TOV     497 non-null    float64
 27  PF      497 non-null    float64
 28  PTS     497 non-null    float64
dtypes: float64(26), object(3)
memory usage: 112.7+ KB
None
              Player Pos  Age   Tm   G  GS    MP   FG   FGA    FG%  ...  \
0   Precious Achiuwa   C   22  TOR  73  28  23.6  3.6   8.3  0.439  ...
1       Steven Adams   C   28  MEM  76  75  26.3  2.8   5.1  0.547  ...
2        Bam Adebayo   C   24  MIA  56  56  32.6  7.3  13.0  0.557  ...
3       Santi Aldama  PF   21  MEM  32   0  11.3  1.7   4.1  0.402  ...
4  LaMarcus Aldridge   C   36  BRK  47  12  22.3  5.4   9.7  0.550  ...

     FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS
0  0.595  2.0  4.5   6.5  1.1  0.5  0.6  1.2  2.1   9.1
1  0.543  4.6  5.4  10.0  3.4  0.9  0.8  1.5  2.0   6.9
2  0.753  2.4  7.6  10.1  3.4  1.4  0.8  2.6  3.1  19.1
3  0.625  1.0  1.7   2.7  0.7  0.2  0.3  0.5  1.1   4.1
4  0.873  1.6  3.9   5.5  0.9  0.3  1.0  0.9  1.7  12.9

[5 rows x 29 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 812 entries, 0 to 811
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  812 non-null    object
 1   Pos     812 non-null    object
 2   Age     812 non-null    int64
 3   Tm      812 non-null    object
 4   G       812 non-null    int64
 5   GS      812 non-null    int64
 6   MP      812 non-null    float64
 7   FG      812 non-null    float64
 8   FGA     812 non-null    float64
 9   FG%     812 non-null    float64
 10  3P      812 non-null    float64
 11  3PA     812 non-null    float64
 12  3P%     812 non-null    float64
 13  2P      812 non-null    float64
 14  2PA     812 non-null    float64
 15  2P%     812 non-null    float64
 16  eFG%    812 non-null    float64
 17  FT      812 non-null    float64
 18  FTA     812 non-null    float64
 19  FT%     812 non-null    float64
 20  ORB     812 non-null    float64
 21  DRB     812 non-null    float64
 22  TRB     812 non-null    float64
 23  AST     812 non-null    float64
 24  STL     812 non-null    float64
 25  BLK     812 non-null    float64
 26  TOV     812 non-null    float64
 27  PF      812 non-null    float64
 28  PTS     812 non-null    float64
dtypes: float64(23), int64(3), object(3)
memory usage: 184.1+ KB
None
                     Player Pos  Age   Tm   G  GS    MP   FG   FGA    FG%  \
0               Bam Adebayo   C   25  MIA  23  23  37.0  7.3  15.1  0.481
1              Santi Aldama  PF   22  MEM   6   0  16.8  2.5   5.5  0.455
2  Nickeil Alexander-Walker  SG   24  MIN   5   4  29.6  3.0   7.0  0.429
3             Grayson Allen  SG   27  MIL   5   5  29.8  3.8   8.2  0.463
4             Jarrett Allen   C   24  CLE   5   5  38.2  4.4   7.2  0.611

   ...    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS
0  ...  0.821  2.7  7.1  9.9  3.7  0.9  0.7  2.7  3.1  17.9
1  ...  1.000  1.2  3.2  4.3  1.2  0.5  0.0  0.3  0.8   6.5
2  ...  0.667  0.2  1.8  2.0  1.4  0.6  0.2  0.8  1.8   8.4
3  ...  0.857  0.2  2.2  2.4  1.8  0.4  0.0  0.8  1.4  11.6
4  ...  0.500  3.0  4.4  7.4  2.4  0.8  1.0  0.6  2.0   9.4

[5 rows x 29 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  217 non-null    object
 1   Pos     217 non-null    object
 2   Age     217 non-null    int64
 3   Tm      217 non-null    object
 4   G       217 non-null    int64
 5   GS      217 non-null    int64
 6   MP      217 non-null    float64
 7   FG      217 non-null    float64
 8   FGA     217 non-null    float64
 9   FG%     217 non-null    float64
 10  3P      217 non-null    float64
 11  3PA     217 non-null    float64
 12  3P%     217 non-null    float64
 13  2P      217 non-null    float64
 14  2PA     217 non-null    float64
 15  2P%     217 non-null    float64
 16  eFG%    217 non-null    float64
 17  FT      217 non-null    float64
 18  FTA     217 non-null    float64
 19  FT%     217 non-null    float64
 20  ORB     217 non-null    float64
 21  DRB     217 non-null    float64
 22  TRB     217 non-null    float64
 23  AST     217 non-null    float64
 24  STL     217 non-null    float64
 25  BLK     217 non-null    float64
 26  TOV     217 non-null    float64
 27  PF      217 non-null    float64
 28  PTS     217 non-null    float64
dtypes: float64(23), int64(3), object(3)
memory usage: 49.3+ KB
None
             Player   Pos  Age   Tm   G  GS    MP   FG   FGA    FG%  ...  \
0  Precious Achiuwa  PF-C   24  TOT  74  18  21.9  3.2   6.3  0.501  ...
1  Precious Achiuwa     C   24  TOR  25   0  17.5  3.1   6.8  0.459  ...
2  Precious Achiuwa    PF   24  NYK  49  18  24.2  3.2   6.1  0.525  ...
3       Bam Adebayo     C   26  MIA  71  71  34.0  7.5  14.3  0.521  ...
4      Ochai Agbaji    SG   23  TOT  78  28  21.0  2.3   5.6  0.411  ...

     FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS
0  0.616  2.6  4.0   6.6  1.3  0.6  0.9  1.1  1.9   7.6
1  0.571  2.0  3.4   5.4  1.8  0.6  0.5  1.2  1.6   7.7
2  0.643  2.9  4.3   7.2  1.1  0.6  1.1  1.1  2.1   7.6
3  0.755  2.2  8.1  10.4  3.9  1.1  0.9  2.3  2.2  19.3
4  0.661  0.9  1.8   2.8  1.1  0.6  0.6  0.8  1.5   5.8

[5 rows x 29 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 735 entries, 0 to 734
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  735 non-null    object
 1   Pos     735 non-null    object
 2   Age     735 non-null    int64
 3   Tm      735 non-null    object
 4   G       735 non-null    int64
 5   GS      735 non-null    int64
 6   MP      735 non-null    float64
 7   FG      735 non-null    float64
 8   FGA     735 non-null    float64
 9   FG%     735 non-null    float64
 10  3P      735 non-null    float64
 11  3PA     735 non-null    float64
 12  3P%     735 non-null    float64
 13  2P      735 non-null    float64
 14  2PA     735 non-null    float64
 15  2P%     735 non-null    float64
 16  eFG%    735 non-null    float64
 17  FT      735 non-null    float64
 18  FTA     735 non-null    float64
 19  FT%     735 non-null    float64
 20  ORB     735 non-null    float64
 21  DRB     735 non-null    float64
 22  TRB     735 non-null    float64
 23  AST     735 non-null    float64
 24  STL     735 non-null    float64
 25  BLK     735 non-null    float64
 26  TOV     735 non-null    float64
 27  PF      735 non-null    float64
 28  PTS     735 non-null    float64
dtypes: float64(23), int64(3), object(3)
memory usage: 166.7+ KB
None

In [18]:
#drop rank column as it doesen't contribute anything for the project, basically the same as an index
def drop_rk_column(df):
    if 'Rk' in df.columns:
        df = df.drop(columns=['Rk'])
    return df
nba_data2021_2022 = drop_rk_column(nba_data2021_2022)
nba_data2022_2023 = drop_rk_column(nba_data2022_2023)
nba_data2023_2024 = drop_rk_column(nba_data2023_2024)
#changing Team column to Tm for later concatenation
def standardize_column_names(df):
    df = df.rename(columns={'Team': 'Tm'})
    return df
nba_data2019_2020_cleaned = standardize_column_names(nba_data2019_2020_cleaned)

In [35]:
# check for NaN in each years Pos column
def check_pos_nans(dataframe, year_label):
    if 'Pos' in dataframe.columns:
        nan_count = dataframe['Pos'].isna().sum()
    else:
        print(f"No 'Pos' column found in the {year_label} dataset.")
    
check_pos_nans(nba_data2019_2020_cleaned, '2019-2020')
check_pos_nans(nba_data2020_2021_cleaned, '2020-2021')
check_pos_nans(nba_data2021_2022, '2021-2022')
check_pos_nans(nba_data2022_2023, '2022-2023')
check_pos_nans(nba_data2023_2024, '2023-2024')

No 'Pos' column found in the 2019-2020 dataset.

In [37]:
#combine datasets with the Pos column to create a mapping for the year 2019-2020
datasets = [nba_data2020_2021_cleaned, nba_data2021_2022, nba_data2022_2023, nba_data2023_2024]
combined_datasets = pd.concat(datasets)

In [40]:
#creating a map and filling positions in 2019-2020
position_mapping = combined_datasets.groupby('Player')['Pos'].agg(lambda x: x.mode().dropna().iloc[0] if not x.mode().empty else np.nan).dropna()
nba_data2019_2020_cleaned['Pos'] = nba_data2019_2020_cleaned['Player'].map(position_mapping)
#check how many positions are filled
filled_positions_count = nba_data2019_2020_cleaned['Pos'].notna().sum()
print(f"Filled positions in 2019-2020 dataset: {filled_positions_count}")

Filled positions in 2019-2020 dataset: 458

In [50]:
#change NaNs to Unknown and check if data is now complete for concatenation
nba_data2019_2020_cleaned['Pos'].fillna('Unknown', inplace=True)
print(nba_data2019_2020_cleaned.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590 entries, 0 to 589
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  590 non-null    object
 1   Age     590 non-null    int64
 2   G       590 non-null    int64
 3   GS      590 non-null    int64
 4   MP      590 non-null    float64
 5   FG      590 non-null    float64
 6   FGA     590 non-null    float64
 7   FG%     590 non-null    float64
 8   3P      590 non-null    float64
 9   3PA     590 non-null    float64
 10  3P%     590 non-null    float64
 11  2P      590 non-null    float64
 12  2PA     590 non-null    float64
 13  2P%     590 non-null    float64
 14  eFG%    590 non-null    float64
 15  FT      590 non-null    float64
 16  FTA     590 non-null    float64
 17  FT%     590 non-null    float64
 18  ORB     590 non-null    float64
 19  DRB     590 non-null    float64
 20  TRB     590 non-null    float64
 21  AST     590 non-null    float64
 22  STL     590 non-null    float64
 23  BLK     590 non-null    float64
 24  TOV     590 non-null    float64
 25  PF      590 non-null    float64
 26  PTS     590 non-null    float64
 27  Tm      590 non-null    object
 28  Pos     590 non-null    object
dtypes: float64(23), int64(3), object(3)
memory usage: 133.8+ KB
None

In [51]:
#concatenating all the data
nba_data_all_years = pd.concat([
    nba_data2019_2020_cleaned, 
    nba_data2020_2021_cleaned, 
    nba_data2021_2022, 
    nba_data2022_2023, 
    nba_data2023_2024
])
print(nba_data_all_years.head()) 
print(nba_data_all_years.info())

             Player   Age     G    GS    MP   FG   FGA    FG%   3P  3PA  ...  \
0   Khris Middleton  28.0  62.0  59.0  29.9  7.6  15.3  0.497  2.4  5.7  ...
1      Eric Bledsoe  30.0  61.0  61.0  27.0  5.5  11.5  0.475  1.2  3.5  ...
2       Brook Lopez  31.0  68.0  67.0  26.7  4.3   9.9  0.435  1.5  4.8  ...
3   Wesley Matthews  33.0  67.0  67.0  24.4  2.5   6.3  0.396  1.6  4.4  ...
4  Donte DiVincenzo  23.0  66.0  24.0  23.0  3.5   7.7  0.455  1.3  3.7  ...

   DRB  TRB  AST  STL  BLK  TOV   PF   PTS   Tm  Pos
0  5.5  6.2  4.3  0.9  0.1  2.2  2.3  20.9  MIL   SF
1  3.9  4.6  5.4  0.9  0.4  2.4  2.1  14.9  MIL   PG
2  3.7  4.6  1.5  0.7  2.4  1.0  2.4  12.0  MIL    C
3  2.1  2.5  1.4  0.6  0.1  0.6  1.5   7.4  MIL   SG
4  3.8  4.8  2.3  1.3  0.3  1.4  1.7   9.2  MIL   SG

[5 rows x 29 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 2851 entries, 0 to 734
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  2851 non-null   object
 1   Age     2851 non-null   float64
 2   G       2851 non-null   float64
 3   GS      2851 non-null   float64
 4   MP      2851 non-null   float64
 5   FG      2851 non-null   float64
 6   FGA     2851 non-null   float64
 7   FG%     2851 non-null   float64
 8   3P      2851 non-null   float64
 9   3PA     2851 non-null   float64
 10  3P%     2851 non-null   float64
 11  2P      2851 non-null   float64
 12  2PA     2851 non-null   float64
 13  2P%     2851 non-null   float64
 14  eFG%    2851 non-null   float64
 15  FT      2851 non-null   float64
 16  FTA     2851 non-null   float64
 17  FT%     2851 non-null   float64
 18  ORB     2851 non-null   float64
 19  DRB     2851 non-null   float64
 20  TRB     2851 non-null   float64
 21  AST     2851 non-null   float64
 22  STL     2851 non-null   float64
 23  BLK     2851 non-null   float64
 24  TOV     2851 non-null   float64
 25  PF      2851 non-null   float64
 26  PTS     2851 non-null   float64
 27  Tm      2851 non-null   object
 28  Pos     2851 non-null   object
dtypes: float64(26), object(3)
memory usage: 668.2+ KB
None